### ISSUE TITLE
No route matches. cari aramada hata veriyor nedeni nedir?

### ISSUE THREAD

**Issue by ismetandac** [ozgur-soft/Parasut.NET#1]
var contacts = _p.SearchContact(new()
                                {
                                    TaxNumber = tax
                                });

hata:

{"Errors":[{"Title":"Not Found","Detail":"No route matches."}],"Data":null}

**Comment by ozgur-yalcin** [comment]
No route matches hatası verdiğine göre yüksek ihtimalle SetCompanyId fonksiyonunu kullanırken firma numarasını hatalı yazmış olabilirsiniz.
